# exposurecomp:
# exposure_lr_init: 0.001 
# exposure_lr_final: 0.0001
# exposure_lr_delay_steps: 5000
# exposure_lr_delay_mult: 0.001 

#train_test_exp: false
resolution: 1
total_frames: 10
start_frame: 1
end_frame: 300
images: "images_downscaled"
frame_folder_name: "colmap_"
iterations: 2000  # round(total_frames / 5 * iterations)
densification_interval: 500  # round(total_frames / 5 * densification_interval)
opacity_reset_interval: 4500  # round(total_frames / 8 * opacity_reset_interval)
densify_until_iter: 17000  # round(total_frames / 3 * densify_until_iter)
save_iterations: [200, 2000, 15000, 30000]
percent_dense: 0.01
optimizer_type: "sparse_adam"
move_pointcloud: false
random_background: false
# white_background: true
# min_opacity: 0.009
densify_grad_threshold: 0.0005
sh_degree: 3
difference_threshold: 0.08
difference_dilation: 0
difference_radius: 0.8
spare_gaussians: 100000

temporal_frame_window: 2
lambda_pos: 0.15
lambda_temporal_smoothing: 0.25
